// <auto-generated />
using System;
using ArchChallenge.CashFlow.Infrastructure.Data.Relational.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArchChallenge.CashFlow.Infrastructure.Data.Relational.Migrations
{
    [DbContext(typeof(CashFlowDbContext))]
    [Migration("20260422052907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchChallenge.CashFlow.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("ST_ACTIVE");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VL_BALANCE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CREATED_AT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_UPDATED_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("ID_USER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_TB_ACCOUNT_USER");

                    b.ToTable("TB_ACCOUNT", (string)null);
                });

            modelBuilder.Entity("ArchChallenge.CashFlow.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_ACCOUNT");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("ST_ACTIVE");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VL_AMOUNT");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VL_BALANCE_AFTER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CREATED_AT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("DS_TRANSACTION");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("ST_TYPE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("TB_TRANSACTION", (string)null);
                });

            modelBuilder.Entity("ArchChallenge.CashFlow.Domain.Shared.Entities.Outbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("ST_ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CREATED_AT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DS_KIND");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("DS_PAYLOAD");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("ST_PROCESSED");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_PROCESSED_AT");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("NR_RETRY_COUNT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("DS_TARGET");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Processed", "Target", "CreatedAt")
                        .HasDatabaseName("IX_OUTBOX_PROCESSED_TARGET_CREATED");

                    b.ToTable("TB_OUTBOX", "outbox");
                });

            modelBuilder.Entity("ArchChallenge.CashFlow.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("ArchChallenge.CashFlow.Domain.Entities.Account", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArchChallenge.CashFlow.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
